name: Email Notification Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Retrieve Gmail credentials from AWS Secrets Manager
        id: get-secret
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id gmail/notification-credentials --query SecretString --output text)
          echo "EMAIL_USERNAME=$(echo $SECRET | jq -r .EMAIL_USERNAME)" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=$(echo $SECRET | jq -r .EMAIL_PASSWORD)" >> $GITHUB_ENV

      - name: Send success email
        if: success()
        run: |
          echo "Pipeline succeeded! Sending email..."
          echo "Subject: Pipeline Succeeded" | sendemail -f "$EMAIL_USERNAME" -t "$EMAIL_USERNAME" -u "Pipeline Succeeded" -m "The pipeline completed successfully." -s smtp.gmail.com:587 -xu "$EMAIL_USERNAME" -xp "$EMAIL_PASSWORD" -o tls=yes

      - name: Send failure email
        if: failure()
        run: |
          echo "Pipeline failed! Sending email..."
          echo "Subject: Pipeline Failed" | sendemail -f "$EMAIL_USERNAME" -t "$EMAIL_USERNAME" -u "Pipeline Failed" -m "The pipeline failed. Please check the logs." -s smtp.gmail.com:587 -xu "$EMAIL_USERNAME" -xp "$EMAIL_PASSWORD" -o tls=yes
